name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: "detekt"
      uses: natiginfo/action-detekt-all@1.15.0-RC1

    - name: Run Lint
      run: ./gradlew lint

    - name: Build with Gradle
      run: ./gradlew build

    - name: Running Unit Tests
      run: ./gradlew testDebugUnitTest
